blank_issues_enabled: false
contact_links:
  - name: Questions or Help
    url: https://github.com/tefirman/confpickem/discussions
    about: For questions or general discussion, please use Discussions instead of opening an issue
